package com.healthtracker.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF0F5238)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFA8E7C5)
val OnPrimaryContainerLight = Color(0xFF002114)
val SecondaryLight = Color(0xFF00696C)
val BackgroundLight = Color(0xFFF8F9FF)
val SurfaceLight = Color(0xFFF8F9FF)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFEFF4FF)
val SurfaceContainerLight = Color(0xFFE5EEFF)
val SurfaceContainerHighLight = Color(0xFFDCE9FF)
val SurfaceContainerHighestLight = Color(0xFFD3E4FE)
val OnSurfaceLight = Color(0xFF0B1C30)
val OnSurfaceVariantLight = Color(0xFF404943)
val OutlineVariantLight = Color(0xFFBFC9C1)
val ErrorLight = Color(0xFFBA1A1A)

val PrimaryDark = Color(0xFF95D4B3)
val OnPrimaryDark = Color(0xFF00391F)
val PrimaryContainerDark = Color(0xFF0E5138)
val OnPrimaryContainerDark = Color(0xFFA8E7C5)
val SecondaryDark = Color(0xFF72D6DA)
val BackgroundDark = Color(0xFF0B1C30)
val SurfaceDark = Color(0xFF0B1C30)
val SurfaceContainerLowestDark = Color(0xFF06111F)
val SurfaceContainerLowDark = Color(0xFF13233A)
val SurfaceContainerDark = Color(0xFF17273D)
val SurfaceContainerHighDark = Color(0xFF223248)
val SurfaceContainerHighestDark = Color(0xFF2D3D53)
val OnSurfaceDark = Color(0xFFDCE9FF)
val OnSurfaceVariantDark = Color(0xFFBFC9C1)
val OutlineVariantDark = Color(0xFF404943)
val ErrorDark = Color(0xFFFFB4AB)
val TertiaryLight = Color(0xFFFB923C)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFF9E4400)
val OnTertiaryContainerLight = Color(0xFFFFD0B8)
val SecondaryContainerLight = Color(0xFF8FF3F6)
val OnSecondaryContainerLight = Color(0xFF007073)
val SurfaceGreenLight = Color(0xFFF0FDF4)
val SurfaceBlueLight = Color(0xFFF0F9FF)
val OutlineLight = Color(0xFF707973)

val TertiaryDark = Color(0xFFFFB690)
val OnTertiaryDark = Color(0xFF783200)
val TertiaryContainerDark = Color(0xFF9E4400)
val OnTertiaryContainerDark = Color(0xFFFFDBCA)
val SecondaryContainerDark = Color(0xFF004F52)
val OnSecondaryContainerDark = Color(0xFF72D6DA)
val SurfaceGreenDark = Color(0xFF0F2818)
val SurfaceBlueDark = Color(0xFF0B1F30)
val OutlineDark = Color(0xFFBFC9C1)
